{% set name = "git-machete" %}
{% set version = "3.34.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1ee92a06fd3f1139326dfb45abfc0813ca64f354bd001ff4117968b0af0d450

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PawelLipski
    - amalota
    - asford
