{% set name = "git-machete" %}
{% set version = "3.18.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/git-machete-{{ version }}.tar.gz
  sha256: 4d8bdde1768c00b9fe6199a2d7fef831491d6fb2e7ed4d56ff3c5b155168b881

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PawelLipski
    - amalota
    - asford
