{% set name = "git-machete" %}
{% set version = "3.17.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/git-machete-{{ version }}.tar.gz
  sha256: 4b070117a5133c7c7e2b8bc2a927574d85edad0202da1d273c98bc7c040a8139

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PawelLipski
    - amalota
    - asford
