{% set name = "git-machete" %}
{% set version = "3.25.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ef554565ff813c6402cfff7ca3655c620bc44d0dd219992e6c957fe73077da5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PawelLipski
    - amalota
    - asford
